### ISSUE TITLE
Show only last week's transactions

### ISSUE THREAD

**Issue by lebobar** [bobar/public-tdb#5]
On devrait préciser que les transactions affichées ne le sont que pour les 7 derniers jours

Gengen
Frankiz_id: 11910

**Comment by tdeo** [comment]
Pour l'instant il y en a 6 mois

**Comment by matthieugendreau** [comment]
Dans ce cas préciser que ce sont les transactions des 6 derniers mois :)

**Comment by tdeo** [comment]
https://github.com/bobar/public-tdb/commit/9915c4488ed71f04f948e896b23411d549bfdee1
