### ISSUE TITLE
Empty state

### ISSUE THREAD

**Issue by lebobar** [bobar/public-tdb#8]
Suggestion: better empty state if no transaction in the last 7 days.
Maybe something like : "Nothing in the last 7 days, we miss you! Click here to see if the BôB is open and come drink a beer."

https://www.invisionapp.com/blog/why-empty-states-deserve-more-design-time/

http://emptystat.es/

Gengen
Frankiz_id: 11910

**Comment by matthieugendreau** [comment]
Current example:

![screenshot from 2017-06-15 15-51-15](https://user-images.githubusercontent.com/5287429/27184518-b23fad52-51e2-11e7-8449-7c93225296c6.png)

**Comment by tdeo** [comment]
https://github.com/bobar/public-tdb/commit/ec8a7a03ebb8db14156cc9ad0ff840f078c30559

![image](https://user-images.githubusercontent.com/6230277/27184604-f1c7a88a-51e2-11e7-96d4-a5faa35ae4cc.png)

**Comment by matthieugendreau** [comment]
:+1:
